apiVersion: v1
kind: Service
metadata:
  name: ms-participantes
spec:
  selector:
    app: ms-participantes
  ports:
  - protocol: TCP
    port: 9091 # Puerto interno del servicio
    targetPort: 9091 # Puerto del contenedor
    nodePort: 30091 # Puerto expuesto en el nodo
  type: NodePort
