apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-eventos
  labels:
    app: ms-eventos
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ms-eventos
  template:
    metadata:
      labels:
        app: ms-eventos
    spec:
      containers:
        - name: ms-eventos
          image: rtineoregistry/ms-eventos:2.0
          args:
            - "--spring.config.additional-location=file:/config/application.yml"
          ports:
            - containerPort: 9081
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 9081
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 9081
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
          env:
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: DB_USERNAME
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: DB_PASSWORD
          resources:
            requests:
              cpu: "200m"
              memory: "200Mi"
            limits:
              cpu: "300m"
              memory: "300Mi"
          volumeMounts:
            - name: config-volume
              mountPath: /config/application.yml
              subPath: application.yml
      volumes:
        - name: config-volume
          configMap:
            name: ms-eventos-config
            items:
              - key: application.yml
                path: application.yml