-- verificación de entorno
SELECT SYS_CONTEXT('USERENV', 'CON_NAME') AS CURRENT_CONTAINER FROM DUAL;

-- Cambiarse a la PDB

ALTER SESSION SET CONTAINER = XEPDB1;

SELECT NAME, CON_ID, CON_NAME FROM V$CONTAINERS;

---CREAR USUARIO
CREATE USER inscrip_admin IDENTIFIED BY admin
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp;

GRANT CONNECT, RESOURCE TO inscrip_admin;
ALTER USER inscrip_admin QUOTA UNLIMITED ON users;

--verificar conexion
CONN inscrip_admin/admin@localhost:1521/xepdb1