apiVersion: v1
kind: Service
metadata:
  name: oracle-db
spec:
  type: NodePort
  selector:
    app: oracle-db
  ports:
    - name: oracle
      protocol: TCP
      port: 1521  # Puerto del contenedor
      targetPort: 1521
      nodePort: 30011  # Puerto expuesto en el nodo
